-- MySQL Script generated by MySQL Workbench
-- Wed Jun 24 15:06:25 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema toolset
-- -----------------------------------------------------
-- lktbl -> linktable
DROP SCHEMA IF EXISTS `toolset` ;

-- -----------------------------------------------------
-- Schema toolset
--
-- lktbl -> linktable
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `toolset` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `toolset` ;

-- -----------------------------------------------------
-- Table `toolset`.`tbl_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `toolset`.`tbl_user` ;

CREATE TABLE IF NOT EXISTS `toolset`.`tbl_user` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(20) NOT NULL COMMENT 'only alphanumeric please',
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(64) NOT NULL COMMENT 'hashed in a secure hash (not md5 !!)\nsha-256',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `toolset`.`tbl_note`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `toolset`.`tbl_note` ;

CREATE TABLE IF NOT EXISTS `toolset`.`tbl_note` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `content` TEXT(1024) NOT NULL,
  `time` DATETIME NOT NULL,
  `author` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_author_id_idx` (`author` ASC) VISIBLE,
  CONSTRAINT `fk_author_id`
    FOREIGN KEY (`author`)
    REFERENCES `toolset`.`tbl_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `toolset`.`lktbl_tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `toolset`.`lktbl_tag` ;

CREATE TABLE IF NOT EXISTS `toolset`.`lktbl_tag` (
  `note` INT UNSIGNED NOT NULL,
  `tag` VARCHAR(45) NOT NULL,
  INDEX `fk_note_id_idx` (`note` ASC) VISIBLE,
  CONSTRAINT `fk_note_id`
    FOREIGN KEY (`note`)
    REFERENCES `toolset`.`tbl_note` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
